package pw.lemmmy.jrogue.dungeon.entities;

public enum EntityAppearance {
	APPEARANCE_PLAYER,
	
	APPEARANCE_JACKAL,
	APPEARANCE_FOX,
	APPEARANCE_HOUND,
	APPEARANCE_HELLHOUND,
	APPEARANCE_ICEHOUND,
	APPEARANCE_SPIDER,
	APPEARANCE_RAT,
	APPEARANCE_SKELETON,
	APPEARANCE_FISH_RED,
	APPEARANCE_FISH_ORANGE,
	APPEARANCE_FISH_YELLOW,
	APPEARANCE_FISH_GREEN,
	APPEARANCE_FISH_BLUE,
	APPEARANCE_FISH_PURPLE,
	APPEARANCE_PUFFERFISH,
	
	APPEARANCE_CHEST,
	APPEARANCE_FOUNTAIN,
	APPEARANCE_CANDLESTICK,
	APPEARANCE_WEAPON_RACK,
	APPEARANCE_WEAPON_RACK_STOCKED,
	
	APPEARANCE_ITEM,

	APPEARANCE_ARROW,
	APPEARANCE_STRIKE
}
