package pw.lemmmy.jrogue.dungeon.entities;

public enum EntityAppearance {
	APPEARANCE_PLAYER,

	APPEARANCE_JACKAL,
	APPEARANCE_FISH_RED,
	APPEARANCE_FISH_ORANGE,
	APPEARANCE_FISH_YELLOW,
	APPEARANCE_FISH_GREEN,
	APPEARANCE_FISH_BLUE,
	APPEARANCE_FISH_PURPLE,

	APPEARANCE_ITEM
}
