version: 2
jobs:
  build:
  	docker:
  	  - image: java:openjdk-8
    working_directory: /tmp
    steps:
      - run:
          name: Building Artifacts
          command: gradle fullDistBuild
      - store_artifacts:
          path: /tmp/build/libs
          destination: jrogue-full-obf-latest
