package pw.lemmmy.jrogue.dungeon.entities.skills;

public enum Skill {
	SKILL_STAFF,
	SKILL_DAGGER,
	SKILL_SHORTSWORD,
	SKILL_LONGSWORD,
	
	SKILL_SPELLS_ATTACK,
	SKILL_SPELLS_HEALING,
	SKILL_SPELLS_ENCHANTMENT,
	SKILL_SPELLS_ESCAPE,
	
	SKILL_TWO_HANDED
}
