package pw.lemmmy.jrogue.dungeon.items;

public enum ItemAppearance {
	APPEARANCE_CORPSE,
	APPEARANCE_STAFF,
	APPEARANCE_DAGGER,
	APPEARANCE_SHORTSWORD,
	APPEARANCE_LONGSWORD,
	APPEARANCE_GOLD,
	APPEARANCE_GEM_WHITE,
	APPEARANCE_GEM_RED,
	APPEARANCE_GEM_ORANGE,
	APPEARANCE_GEM_YELLOW,
	APPEARANCE_GEM_LIME,
	APPEARANCE_GEM_GREEN,
	APPEARANCE_GEM_CYAN,
	APPEARANCE_GEM_BLUE,
	APPEARANCE_GEM_PURPLE,
	APPEARANCE_GEM_PINK,
	APPEARANCE_GEM_BLACK,
}
