package jr.dungeon.items;

public enum ItemAppearance {
	// COMESTIBLES
	
	APPEARANCE_CORPSE,
	APPEARANCE_BREAD,
	APPEARANCE_APPLE,
	APPEARANCE_ORANGE,
	APPEARANCE_LEMON,
	APPEARANCE_BANANA,
	APPEARANCE_CARROT,
	APPEARANCE_MELON_SLICE,
	APPEARANCE_MELON,
	APPEARANCE_WATERMELON_SLICE,
	APPEARANCE_WATERMELON,
	APPEARANCE_CHERRIES,
	APPEARANCE_EGGS,
	APPEARANCE_CORN,
	APPEARANCE_POTATO_RAW,
	
	// WEAPONS
	
	APPEARANCE_STAFF,
	APPEARANCE_DAGGER,
	APPEARANCE_SHORTSWORD,
	APPEARANCE_LONGSWORD,
	
	APPEARANCE_BOW,
	APPEARANCE_ARROW,
	
	// SPELLBOOK
	
	APPEARANCE_SPELLBOOK,
	
	// VALUABLES
	
	APPEARANCE_GOLD,
	APPEARANCE_GEM_WHITE,
	APPEARANCE_GEM_RED,
	APPEARANCE_GEM_ORANGE,
	APPEARANCE_GEM_YELLOW,
	APPEARANCE_GEM_LIME,
	APPEARANCE_GEM_GREEN,
	APPEARANCE_GEM_CYAN,
	APPEARANCE_GEM_BLUE,
	APPEARANCE_GEM_PURPLE,
	APPEARANCE_GEM_PINK,
	APPEARANCE_GEM_BLACK,
	
	// POTIONS
	
	APPEARANCE_POTION_EMPTY,
	APPEARANCE_POTION_LABEL_EMPTY,
	APPEARANCE_POTION_CORK_EMPTY,
	APPEARANCE_POTION_CORK_LABEL_EMPTY,
	APPEARANCE_POTION_FAT_EMPTY,
	APPEARANCE_POTION,
	APPEARANCE_POTION_LABEL,
	APPEARANCE_POTION_CORK,
	APPEARANCE_POTION_CORK_LABEL,
	APPEARANCE_POTION_FAT,
	APPEARANCE_THERMOMETER
}
