package jr.dungeon.entities;

public enum EntityAppearance {
	APPEARANCE_PLAYER,
	
	APPEARANCE_JACKAL,
	APPEARANCE_FOX,
	APPEARANCE_HOUND,
	APPEARANCE_HELLHOUND,
	APPEARANCE_ICEHOUND,
	APPEARANCE_SPIDER,
	APPEARANCE_RAT,
	APPEARANCE_SKELETON,
	APPEARANCE_GOBLIN,
	APPEARANCE_GOBLIN_ZOMBIE,
	APPEARANCE_LIZARD,
	APPEARANCE_MOLD_RED,
	APPEARANCE_MOLD_YELLOW,
	APPEARANCE_MOLD_GREEN,
	APPEARANCE_MOLD_BLUE,
	APPEARANCE_FISH_RED,
	APPEARANCE_FISH_ORANGE,
	APPEARANCE_FISH_YELLOW,
	APPEARANCE_FISH_GREEN,
	APPEARANCE_FISH_BLUE,
	APPEARANCE_FISH_PURPLE,
	APPEARANCE_PUFFERFISH,
	
	APPEARANCE_CHEST,
	APPEARANCE_FOUNTAIN,
	APPEARANCE_FOUNTAIN_FROZEN,
	APPEARANCE_CANDLESTICK,
	APPEARANCE_CANDLESTICK_EXTINGUISHED,
	APPEARANCE_WEAPON_RACK,
	APPEARANCE_WEAPON_RACK_STOCKED,
	APPEARANCE_ALTAR,
	APPEARANCE_GRAVESTONE,
	
	APPEARANCE_ITEM,
	
	APPEARANCE_ARROW,
	APPEARANCE_STRIKE,
	
	APPEARANCE_LIGHT_ORB,
	
	APPEARANCE_STALAGMITES,
	
	APPEARANCE_CAVE_CRYSTAL_WHITE,
	APPEARANCE_CAVE_CRYSTAL_BLUE,
	APPEARANCE_CAVE_CRYSTAL_CYAN,
	APPEARANCE_CAVE_CRYSTAL_SMALL_WHITE,
	APPEARANCE_CAVE_CRYSTAL_SMALL_BLUE,
	APPEARANCE_CAVE_CRYSTAL_SMALL_CYAN
}
